# Generated by Django 4.0.4 on 2022-08-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmanagement',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dietmanagement',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
