# Generated by Django 4.0.4 on 2022-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_dietmanagement_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmanagement',
            name='height',
            field=models.CharField(max_length=199),
        ),
        migrations.AlterField(
            model_name='dietmanagement',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
