# Generated by Django 4.0.4 on 2022-05-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwordreset',
        ),
    ]
