# Generated by Django 4.0.4 on 2022-05-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_delete_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='numbers',
        ),
    ]
