# Generated by Django 4.0.4 on 2022-08-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_dietmanagement_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietmanagement',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dietmanagement',
            name='height',
        ),
        migrations.RemoveField(
            model_name='dietmanagement',
            name='result',
        ),
        migrations.RemoveField(
            model_name='dietmanagement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dietmanagement',
            name='weight',
        ),
    ]
