# Generated by Django 4.0.4 on 2022-05-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_remove_contact_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
