# Generated by Django 4.0.4 on 2022-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_rename_email_contact_email_rename_name_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
