# Generated by Django 4.0.4 on 2022-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_remove_dietmanagement_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Carausel/%y/%m/%d')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
            ],
        ),
    ]
