# Generated by Django 4.0.4 on 2022-05-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_customuser_address_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil_pic',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
