# Generated by Django 4.0.4 on 2022-05-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_customuser_profil_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profil_pic',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
