# Generated by Django 4.0.4 on 2022-05-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_customuser_profil_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profil_pic',
            new_name='image',
        ),
    ]
