# Generated by Django 4.0.4 on 2022-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_rename_profil_pic_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
