# Generated by Django 4.0.4 on 2022-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
