# Generated by Django 4.0.4 on 2022-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_customuser_is_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='pending', max_length=100, null=True),
        ),
    ]
