# Generated by Django 4.0.4 on 2022-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_trainerdepartment_trainer_member_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdepartment',
            name='department',
            field=models.CharField(choices=[('GYM', 'GYM'), ('Cardio', 'Cardio'), ('jumba', 'jumba')], max_length=100),
        ),
    ]
