# Generated by Django 4.0.4 on 2022-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_alter_trainerdepartment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdepartment',
            name='department',
            field=models.CharField(choices=[('GYM', 'GYM'), ('Cardio', 'Cardio'), ('zumba', 'zumba')], max_length=100),
        ),
    ]
